name: 🚀 Deploy SAXONARA.com via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Syncing Files
    runs-on: ubuntu-latest

    # AIXÒ ÉS EL QUE EVITARÀ QUE ES SOLAPIN PROCESSOS
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true


    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # --- PAS 1: PUJAR LA WEB PRINCIPAL (ARREL) ---
    - name: 📂 FTP Upload Main Web
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: ./saxonara.com/
        # Exclou la carpeta de codi d'Astro perquè no es barregi amb la web principal
        exclude: |
          .git*
          .github/**
